export class SchemaQuestionario {
    static schema = {
        name: 'QuestionarioSchema',
        properties: {
            dataQuestionario: { type: 'int' },
            q01: { type: 'int' },
            q02: { type: 'int' },
            q03: { type: 'int' },
            q04: { type: 'int' },
            q05: { type: 'int' },
            q06: { type: 'int' },
            q07: { type: 'int' },
            q08: { type: 'int' },
            q09: { type: 'int' },
            q10: { type: 'int' },
            q11: { type: 'int' },
            q12: { type: 'int' },
            q13: { type: 'int' },
            q14: { type: 'int' },
            q15: { type: 'int' },
            q16: { type: 'int' },
            q17: { type: 'int' },
            q18: { type: 'int' },
            q19: { type: 'int' },
            q20: { type: 'int' },
            q21: { type: 'int' },
            q22: { type: 'int' },
            q23: { type: 'int' },
            q24: { type: 'int' },
            q25: { type: 'int' },
            q26: { type: 'int' },
            q27: { type: 'int' },
            q28: { type: 'int' },
            q29: { type: 'int' },
            q30: { type: 'int' },
            q31: { type: 'int' },
            q32: { type: 'int' },
            q33: { type: 'int' },
            q34: { type: 'int' },
            q35: { type: 'int' },
            setor: { type: 'SetorSchema?' },
            id: { type: 'int?' }
        }
    }
}